### ISSUE TITLE
Feature Request Main Menu Icon

### ISSUE THREAD

**Issue by rajeshdalsaniya** [DeKoServidoni/OMFM#1]
Hi Andre I recommend one feature on main icon of Feb Menu. When menu loads hamburger menu menu Icon will show. When user click on Fab Menu Icon X (close Icon will show) in short use two images for Main menu 
1. For normal state 
2. Active State
-----------------
Can able to Resize floating button (mini, normal)

**Comment by DeKoServidoni** [comment]
Hi, added 2 new parameters to resize the fab buttons
<app:size_main_button="@integer/omfm_fab_size_normal"> [optional] size of the main button
<app:size_secondary_buttons="@integer/omfm_fab_size_mini"> [optional] size of the secondary buttons
