### ISSUE TITLE
Make primary button an option too

### ISSUE THREAD

**Issue by f3yisayo** [DeKoServidoni/OMFM#10]
Thank you for the last update!

It would be nice to also have the first primary button as an option with a label too, currently the primary button only opens the hidden options.

Something like this below: 

<img width="420" alt="screen shot 2018-01-09 at 3 04 14 am" src="https://user-images.githubusercontent.com/9140532/34701677-d41e2e6c-f4e9-11e7-8126-7f9329f220dd.png">

Also a tiny little bit of padding to the left and right between the labels and the white background.

**Comment by DeKoServidoni** [comment]
Hello @f3yisayo the new version 1.1.0 is live with this changes.
Thanks :)
