### ISSUE TITLE
Main Button label shows with no text

### ISSUE THREAD

**Issue by acmeuno** [DeKoServidoni/OMFM#15]
Setting main menu item title to "" shows a bit of a label background with no text next to the main button.
Could be because the extra padding recently added?

**Comment by DeKoServidoni** [comment]
Hello @acmeuno if the app:enable_main_as_action is true and the item title is "" this problem occurs but if app:enable_main_as_action is false it work as expected.

I will fix this issue and update the library

Thanks :)

**Comment by acmeuno** [comment]
My bad! Thought that was the correct configuration.


Thanks!!!

**Comment by DeKoServidoni** [comment]
Hi, fixed the bug, you can now update to 1.1.1 
Thanks!
