### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by nicemak** [DeKoServidoni/OMFM#31]
In may this library won't be available from JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please migrate this library to some other repository

**Comment by nicemak** [comment]
@DeKoServidoni @FANMixco @f3yisayo @aolivafaura

**Comment by FANMixco** [comment]
Hi @nicemak, I updated the change, but I'm not the owner of the project. I left a pull request.

**Comment by DeKoServidoni** [comment]
done

**Comment by nicemak** [comment]
> Could not find com.github.dekoservidoni:omfm:1.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/dekoservidoni/omfm/1.1.1/omfm-1.1.1.pom
       - https://repo.maven.apache.org/maven2/com/github/dekoservidoni/omfm/1.1.1/omfm-1.1.1.pom
       - https://jitpack.io/com/github/dekoservidoni/omfm/1.1.1/omfm-1.1.1.pom

**Comment by FANMixco** [comment]
Hi @nicemak, in the worst case just build it and add the aar to your project.
