### ISSUE TITLE
Is it a way to close the menu?

### ISSUE THREAD

**Issue by FANMixco** [DeKoServidoni/OMFM#5]
Hi Andre, 

I have a question, is it any way to close the menu when you do click in any option? Or if you do click on the back button? Thanks for your awesome plugin!

**Comment by FANMixco** [comment]
I found how to do it, if it's useful for anyone this is my solution (It's from C#, but you could adapt it):
`
        //Declare the button globally, it can be locally too.
        FloatingActionButton mainButton;
         
        //Resource is the R class
        mainButton = FindViewById<FloatingActionButton>(Resource.Id.main_option);

        public void OnOptionClick(int optionId)
        {
           //You can perform the auto-click before the actions are executed and it will hide it.
            mainButton.PerformClick();
            switch (optionId)
            {
                case Resource.Id.option1:
                    break;
            }
        }

`

**Comment by DeKoServidoni** [comment]
Hello Federico, thanks for the question.
I didn't implemented yet, it's on my update package that will come soon hahahaha. You can achieve this with the performClick(), as you did in your solution, or you can call the onClick, from OneMoreFabMenu, passing null as argument (it's not the best solution but works too)

:)

**Comment by FANMixco** [comment]
Hi Andre,

Also, I found a another strange if you have a button in the Layout and you display the menu, you can still click it even if it's not visible. Do you know how to know if the MainButton was clicked? I think if we know that it could be a trick to fix it :). Thanks!

**Comment by DeKoServidoni** [comment]
Hello Federico, 
Really? I will fix.
Thanks for the feedbacks :D

**Comment by DeKoServidoni** [comment]
Hi Federico, i merged updates for some issues, so i will close this. If you found any other issue, please open a new one
thanks :)
