### ISSUE TITLE
Disable rotation of primary button

### ISSUE THREAD

**Issue by f3yisayo** [DeKoServidoni/OMFM#9]
Hi, thank you so much for this library! You rock!

Is there anyway to disable rotation of the first button in the menu? Would be nice to have an option to also turn off rotation for cases where rotating the icon isn't necessary.

**Comment by DeKoServidoni** [comment]
Sure, I will work on that :)

**Comment by DeKoServidoni** [comment]
Hello, i update a new version with this feature:
just add app:rotate_main_button="false" in your OneMoreFabMenu layout to turn off rotation :)
the default is true.

Thanks :)
